import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

const c = { ink: '#0f172a', green: '#1b3c35', teal: '#0d9488', muted: '#64748b', line: '#e2e8f0', canvas: '#f8fafc', white: '#fff' };

export const flowScreens = {
  AccountPhone: { title: 'Welcome to Acredo 👋', subtitle: 'Your trusted way to send and carry parcels.', section: "Let's get your account set up", fields: ['Mobile number'], action: 'Continue', next: 'AccountOtp', step: '1 of 4' },
  AccountOtp: { title: 'Verify your mobile number', subtitle: 'Enter the code we sent to your phone.', fields: ['Verification code'], action: 'Verify and continue', next: 'AccountAbout', step: '2 of 4' },
  AccountAbout: { title: 'Tell us a little about yourself', subtitle: 'Your profile helps the community know who they are travelling with.', fields: ['Full name', 'Email address'], action: 'Continue', next: 'AccountIdentity', step: '3 of 4' },
  AccountIdentity: { title: 'Verify your identity', subtitle: 'Upload a valid identity document to keep every delivery trusted.', cards: ['Aadhaar card', 'Driving licence', 'Passport'], action: 'Submit documents', next: 'VerificationSubmitted', step: '4 of 4' },
  VerificationSubmitted: { title: "You're all set!", subtitle: 'Your documents have been submitted for verification. We’ll notify you once your account is approved.', cards: ['What happens next?', 'Your documents are reviewed securely', 'You can explore the app while we verify your account'], action: 'Go to sign in', next: 'Login' },
  Profile: { title: 'Profile', subtitle: 'Manage your account and verification details.', cards: ['Personal information', 'Aadhaar Verified', 'Driving Licence', 'Payment methods', 'Help and support', 'Log out'] },
  StartEarning: { title: 'Start Earning While Travelling', subtitle: 'Carry parcels along your journey and earn from your available space.', cards: ['Driving Licence', 'Identity verification', 'Vehicle details'], action: 'Continue verification', next: 'UploadedDocuments' },
  UploadedDocuments: { title: 'Uploaded Documents', subtitle: 'All documents successfully verified. You are ready to start travelling and earning!', cards: ['Driving Licence', 'driving_licence.jpg', 'Uploaded'], action: 'Add a trip', next: 'CreateTrip' },
  PreferredDates: { title: 'When would you like your parcel to be delivered?', subtitle: 'Select one or more dates that work for you.', cards: ['August 2026', '18 Aug', '19 Aug', '20 Aug'], action: 'Continue', next: 'PickupDetails', step: '1/8' },
  PickupDetails: { title: 'Where should the parcel be picked up?', subtitle: 'Choose a city and add places where the traveller can conveniently collect your parcel.', fields: ['Pickup city', 'Pickup point'], action: 'Continue', next: 'DropDetails', step: '2/8' },
  DropDetails: { title: 'Where should the parcel be delivered?', subtitle: 'Choose the destination city and add places where the traveller can conveniently deliver the parcel.', fields: ['Drop city', 'Delivery point'], action: 'Continue', next: 'ReceiverDetails', step: '3/8' },
  ReceiverDetails: { title: 'Who will receive the parcel?', subtitle: 'Enter the details of the person receiving your parcel.', fields: ['Receiver name', 'Mobile number'], action: 'Continue', next: 'ParcelSafety', step: '4/8' },
  ParcelSafety: { title: 'Before you continue', subtitle: 'Some items cannot be sent through ACREDO. Make sure your parcel complies with safety guidelines.', cards: ['Illegal substances', 'Weapons and ammunition', 'Explosives and flammables', 'I agree my parcel follows these guidelines'], action: 'Continue', next: 'ParcelDetails', step: '5/8' },
  ParcelDetails: { title: 'Tell us about your parcel', subtitle: 'This helps travellers understand whether the parcel will fit in their available space.', fields: ['Parcel size', 'Category', 'Describe your parcel'], cards: ['Small', 'Medium', 'Large'], action: 'Continue', next: 'ParcelPhotos', step: '6/8' },
  ParcelPhotos: { title: 'Add parcel photos', subtitle: 'Help travellers understand what they will be carrying.', cards: ['Front of parcel', 'Side of parcel'], action: 'Continue', next: 'ReviewParcel', step: '7/8' },
  ReviewParcel: { title: 'Review your parcel request', subtitle: 'Double-check all entered information to ensure accurate routing and matches.', cards: ['Preferred delivery dates', 'Pickup details', 'Drop details', 'Receiver details', 'Parcel details', 'Parcel photos'], action: 'Find travellers', next: 'FindingTravellers', step: '8/8' },
  FindingTravellers: { title: 'Finding travellers for you', subtitle: 'We’re looking for verified travellers who are travelling on your route and can carry your parcel.', cards: ['Matching preferred dates  ·  Checked', 'Checking suitable pickup points  ·  Checked'], action: 'View travellers', next: 'MatchedTravellers' },
  MatchedTravellers: { title: 'Travellers for your parcel', subtitle: 'Choose a traveller who best suits your preferred dates and route.', cards: ['Rajesh Kumar  ·  Identity verified  ·  Car  ·  4.9', 'Pune → Mumbai  ·  18 Aug 2026  ·  5:10 AM', 'Priya Sharma  ·  Identity verified  ·  Car  ·  4.8', 'Amit Patel  ·  Identity verified  ·  Car  ·  4.7'], action: 'View trip details', next: 'TravellerTripDetails' },
  TravellerTripDetails: { title: 'Trip Details', subtitle: 'Review the trip details and parcel capacity before sending a request.', cards: ['Rajesh Kumar  ·  Identity verified', 'Member since 2024  ·  4.9', 'Pune → Mumbai', '18 Aug 2026 · 5:10 AM', 'Available parcel capacity'], action: 'Send request', next: 'RequestSent' },
  RequestDetails: { title: 'Parcel Request', subtitle: 'Review the sender and parcel details before responding.', cards: ['Pune → Mumbai', 'Sender · Pratiksha Pawar', 'Parcel size · Small', 'Clothes · 2 pairs packed in a small box'], action: 'Accept request', next: 'TravellerAccepted' },
  TravellerAccepted: { title: 'Request Accepted! 🎉', subtitle: 'You’ve accepted this parcel request.', cards: ['Summary', 'Pune → Mumbai', 'Pickup and delivery details'], action: 'Continue', next: 'TravellerBookingConfirmed' },
  TravellerBookingConfirmed: { title: 'Booking Confirmed! ✅', subtitle: 'The sender has completed the payment. You can now coordinate with the sender.', cards: ['Summary', 'Pune → Mumbai', 'Contact sender'], action: 'Back to home', next: 'Home' },
  RequestSent: { title: 'Request Sent', subtitle: 'We’ve notified the traveller. We’ll update you once they respond.', cards: ['Booking summary', 'Awaiting response', 'Pune → Mumbai'], action: 'Track request', next: 'RequestAccepted' },
  SenderAccepted: { title: 'Request Accepted!', subtitle: 'Your request was accepted! Complete payment within 2 hours to confirm your booking.', cards: ['Payment timer', '01:47:32', 'Rajesh Kumar · Verified traveller · Car'], action: 'Continue to payment', next: 'Payment' },
  Payment: { title: 'Complete Your Payment', subtitle: 'Choose your preferred payment method to confirm the booking.', cards: ['Booking summary', 'Pune → Mumbai', 'UPI', 'Credit or debit card', 'Net banking'], action: 'Pay securely', next: 'BookingConfirmed' },
  BookingConfirmed: { title: 'Booking Confirmed', subtitle: 'Payment was successful and the parcel booking is confirmed.', cards: ['From Pune', 'To Mumbai', 'Your traveller', 'Rajesh Kumar'], action: 'Track your parcel', next: 'ParcelTracking' },
  ParcelTracking: { title: 'Track Your Parcel', subtitle: 'Pune → Mumbai', cards: ['In Transit', 'Pune', 'Mumbai', 'Your traveller', 'Rajesh Kumar', 'Parcel updates'], action: 'View tracking details', next: 'ReceiverTracking' },
  ArrivingSoon: { title: 'Track Your Parcel', subtitle: 'Parcel ID · AC-9847-MH2', cards: ['Arriving Soon', 'Pune → Mumbai', 'Your parcel is nearing its destination', 'Traveller details'], action: 'View delivery status', next: 'ReadyForDelivery' },
  ReadyForDelivery: { title: 'Track Your Parcel', subtitle: 'Parcel ID · AC-9847-MH2', cards: ['Ready for Delivery', 'Sender information', 'Parcel information', 'Delivery information', 'Proof of delivery'], action: 'Back to home', next: 'Home' },
  ReceiverTracking: { title: 'Track Your Parcel', subtitle: 'Pune → Mumbai', cards: ['In Transit', 'Sender · Pratiksha Pawar', 'Traveller · Rajesh Kumar', 'Estimated delivery'], action: 'Back to home', next: 'Home' },
  SenderUpcoming: { title: 'Upcoming', subtitle: 'Booking ID: AC-9847-MH2', cards: ['From Pune', 'To Mumbai', 'Your traveller · Rajesh Kumar', '18 Aug 2026'], action: 'Track parcel', next: 'SenderOnWay' },
  SenderOnWay: { title: 'On the Way', subtitle: 'Booking ID: AC-9847-MH2', cards: ['From Pune', 'To Mumbai', 'Your traveller is approaching · Est. arrival 8 mins'], action: 'Ready for pickup', next: 'SenderReady' },
  SenderReady: { title: 'Ready for Pickup', subtitle: 'Your traveller is at the pickup location.', cards: ['From Pune', 'To Mumbai', 'Pickup verification'], action: 'View parcel', next: 'ParcelTracking' },
  SenderInTransit: { title: 'In Transit', subtitle: 'Booking ID: AC-9847-MH2', cards: ['From Pune', 'To Mumbai', 'Your parcel is on its way'], action: 'Track parcel', next: 'ParcelTracking' },
  SenderDelivered: { title: 'Parcel Delivered', subtitle: 'Successfully completed on 18 Aug 2026, 02:45 PM', cards: ['Booking ID: AC-9847-MH2', 'Delivered', 'Rate your traveller'], action: 'Back to home', next: 'Home' },
  TodayTrip: { title: 'Today’s Trip', subtitle: '18 Aug 2026 · Traveller: Rajesh Kumar', cards: ['From Pune', 'To Mumbai', 'Parcels on this route', 'Small · Clothes · Awaiting pickup'], action: 'Start today’s trip', next: 'TripInProgress' },
  TripInProgress: { title: 'Trip In Progress', subtitle: 'ID: AC-9847-MH2', cards: ['Pune → Mumbai', 'Manage parcels', 'Small · Clothes · Awaiting pickup'], action: 'Pick up parcel', next: 'ConfirmPickup' },
  ConfirmPickup: { title: 'Confirm Pickup', subtitle: 'Pickup summary', cards: ['Sender · Pratiksha Pawar', 'Parcel type · Small · Clothes', 'Pickup point'], fields: ['Enter pickup OTP'], action: 'Confirm pickup', next: 'DeliverParcel' },
  DeliverParcel: { title: 'Deliver Parcel', subtitle: 'Delivery summary', cards: ['Receiver · Neha Deshmukh', 'Parcel type · Small · Clothes', 'Drop point'], action: 'Confirm delivery', next: 'ConfirmDelivery' },
  ConfirmDelivery: { title: 'Confirm Delivery', subtitle: 'Delivery photo proof · Captured successfully', fields: ['Enter delivery OTP'], action: 'Submit delivery', next: 'InstantPayout' },
  InstantPayout: { title: 'Delivery Confirmed!', subtitle: 'Payment of ₹349 has been credited to your account instantly.', cards: ['Payout details', 'Amount credited · ₹349'], action: 'Trip summary', next: 'TripCompleted' },
  TripCompleted: { title: 'Trip Completed', subtitle: 'All parcels have been successfully delivered to their destinations.', cards: ['Trip summary', 'Route · Pune → Mumbai', 'Trip date · 18 Aug 2026'], action: 'Back to home', next: 'Home' },
  ReceiverUpcoming: { title: 'Track Your Parcel', subtitle: 'Pune → Mumbai', cards: ['Upcoming', 'Booking ID: AC-9847-MH2', 'Your parcel is booked'], action: 'Track in transit', next: 'ReceiverInTransit' },
  ReceiverInTransit: { title: 'Track Your Parcel', subtitle: 'Pune → Mumbai', cards: ['In Transit', 'Est. delivery · 02:30 PM', 'Booking ID: AC-9847-MH2'], action: 'View delivery', next: 'ReceiverDelivered' },
  ReceiverDelivered: { title: 'Track Your Parcel', subtitle: 'Pune → Mumbai', cards: ['Delivered', 'Booking ID: AC-9847-MH2', 'Your parcel was delivered'], action: 'Back to home', next: 'Home' },
  CancelTrip: { title: 'Cancel Trip', subtitle: 'All confirmed senders will be immediately notified and fully refunded. This action cannot be undone.', cards: ['Why are you cancelling?', 'Plans changed', 'Vehicle issue', 'Emergency'], action: 'Cancel trip', next: 'Home', destructive: true },
  CancelBooking: { title: 'Cancel Booking', subtitle: 'Booking ID: AC-9847-MH2', cards: ['Confirmed', 'From Pune', 'To Mumbai', 'Why are you cancelling?'], action: 'Cancel booking', next: 'Home', destructive: true },
  NoTravellers: { title: 'No Travellers Found', subtitle: 'We couldn’t find any travellers on your route for the selected dates. Try adjusting your dates or check back later.', cards: ['From Pune', 'To Mumbai'], action: 'Change dates', next: 'PreferredDates' },
  RequestDeclined: { title: 'Request Not Accepted', subtitle: 'This traveller couldn’t take your parcel. Don’t worry — there are other travellers on your route.', cards: ['Declined traveller · Rajesh Kumar'], action: 'See other travellers', next: 'MatchedTravellers' },
  PaymentFailed: { title: 'Payment Failed', subtitle: 'We couldn’t complete your payment. Please try again or use a different payment method.', cards: ['Payment timer · 01:32:15'], action: 'Try payment again', next: 'Payment' },
  RequestExpired: { title: 'Request Expired', subtitle: 'Payment was not completed within 2 hours. The traveller’s capacity has been released.', cards: ['From Pune', 'To Mumbai'], action: 'Find travellers', next: 'MatchedTravellers' },
};

export default function DesignFlowScreen({ route, navigation }) {
  const spec = flowScreens[route.name] || flowScreens.Home;
  const [values, setValues] = useState({});
  const go = () => {
    if (!spec.next) { navigation.goBack(); return; }
    navigation.navigate(spec.next);
  };
  return <View style={s.page}>
    <View style={s.top}><View style={s.brandMark}><Text style={s.brandIcon}>◇</Text></View><Text style={s.brand}>ACREDO</Text><Text style={s.language}>English⌄</Text></View>
    <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      {!!spec.step && <View style={s.progress}><Text style={s.progressText}>ACCOUNT SETUP</Text><Text style={s.progressText}>{spec.step}</Text></View>}
      <Text style={s.title}>{spec.title}</Text>
      {!!spec.subtitle && <Text style={s.subtitle}>{spec.subtitle}</Text>}
      {!!spec.section && <Text style={s.section}>{spec.section}</Text>}
      {!!spec.fields?.length && <View style={s.form}>{spec.fields.map((field, i) => <View key={field}><Text style={s.label}>{field}</Text><TextInput style={s.input} placeholder={field} placeholderTextColor="#94a3b8" value={values[field] || ''} onChangeText={v => setValues({ ...values, [field]: v })} keyboardType={/phone|mobile|otp|number/i.test(field) ? 'phone-pad' : 'default'} /></View>)}</View>}
      {!!spec.cards?.length && <View style={s.cards}>{spec.cards.map((item, i) => <Pressable key={`${item}-${i}`} onPress={() => spec.next && item.includes('traveller') && navigation.navigate('TravellerTripDetails')} style={s.card}><View style={s.cardIcon}><Text style={s.cardGlyph}>{i % 2 ? '↗' : '□'}</Text></View><Text style={s.cardText}>{item}</Text><Text style={s.chevron}>›</Text></Pressable>)}</View>}
    </ScrollView>
    {!!spec.action && <View style={s.footer}><Pressable style={[s.button, spec.destructive && s.danger]} onPress={go}><Text style={s.buttonText}>{spec.action}</Text></Pressable><Text style={s.footnote}>Secure, trusted parcel delivery with ACREDO</Text></View>}
  </View>;
}

const s = StyleSheet.create({ page:{flex:1,backgroundColor:c.canvas}, top:{height:60,paddingHorizontal:24,flexDirection:'row',alignItems:'center',gap:8,borderBottomWidth:1,borderBottomColor:'#f1f5f9'},brandMark:{width:30,height:30,borderRadius:9,backgroundColor:c.green,alignItems:'center',justifyContent:'center'},brandIcon:{color:c.white,fontSize:21,fontWeight:'700'},brand:{fontSize:16,fontWeight:'800',letterSpacing:1,color:c.ink,flex:1},language:{borderRadius:18,borderWidth:1,borderColor:c.line,backgroundColor:c.white,paddingHorizontal:12,paddingVertical:7,color:c.ink,fontSize:12},content:{paddingHorizontal:24,paddingTop:28,paddingBottom:24},progress:{flexDirection:'row',justifyContent:'space-between',marginBottom:16},progressText:{fontSize:12,fontWeight:'700',color:c.green},title:{fontSize:27,fontWeight:'800',lineHeight:34,color:c.ink,marginBottom:8},subtitle:{fontSize:15,lineHeight:23,color:c.muted,marginBottom:24},section:{fontSize:14,fontWeight:'700',textTransform:'uppercase',color:c.ink,marginBottom:16},form:{gap:16,marginBottom:20},label:{fontSize:12,fontWeight:'600',color:c.muted,marginBottom:7},input:{height:50,borderWidth:1.5,borderColor:c.line,borderRadius:12,paddingHorizontal:14,backgroundColor:c.white,color:c.ink,fontSize:15},cards:{gap:10,marginTop:5},card:{minHeight:60,borderWidth:1,borderColor:c.line,borderRadius:14,backgroundColor:c.white,paddingHorizontal:14,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:12},cardIcon:{width:34,height:34,borderRadius:10,backgroundColor:'#eff6f4',alignItems:'center',justifyContent:'center'},cardGlyph:{fontSize:17,color:c.green,fontWeight:'700'},cardText:{flex:1,color:c.ink,fontSize:14,fontWeight:'600',lineHeight:20},chevron:{fontSize:23,color:c.muted},footer:{paddingHorizontal:24,paddingTop:12,paddingBottom:14,borderTopWidth:1,borderTopColor:'#eef2f5'},button:{height:52,borderRadius:12,backgroundColor:c.green,alignItems:'center',justifyContent:'center'},danger:{backgroundColor:'#b42318'},buttonText:{fontSize:16,fontWeight:'700',color:c.white},footnote:{textAlign:'center',marginTop:10,fontSize:11,color:c.muted} });
